### ISSUE TITLE
Write guidelines for writing automated backend tests

### ISSUE THREAD

**Issue by ethanjli** [pez-globo/pufferfish-software#49]
We will need to write guidelines & best practices for how to clearly write and document automated tests on the backend, using pytest (and maybe also using hypothesis, I've been using that too). These guidelines could go into Notion as a first step, though it could also make sense to eventually have them be compiled into our Sphinx documentation package. Anyways, we'll eventually need to incorporate them into our regulatory documentation too, so we can just put them on Notion for now.

**Comment by Tanmay06** [comment]
From our discussions it seems like BDD is the right way to go, as it would help us in smoothly integrating our code with MatrixReq documents. But then, what should be the scope of this issue ? Would it be suffice to include guidelines in Notion through hyperlinks to standard BDD documents, or do we also need to include a sample of feature test migrated to BDD style in our repo ?

**Comment by ethanjli** [comment]
(For future reference, summarizing what we've discussed,) let's have samples of BDD-style tests of different kinds of feature (e.g. filters, I/O if possible, utility functions) as well as guidelines in Notion

**Comment by Tanmay06** [comment]
I've already written few samples of BDD-style tests for `test_crcelements`, which covers utility functions and filters, and I've also included the guidelines in the #204. If the style looks good I'll also update the docstring for `test_fileiopy`.
